[features]
seeds = false
skip-lint = false
[programs.localnet]
gif_portal = "GWnfF71VZSD6teEg6qjrCycnVAaidHFg8z4VHpJpdwyr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mythra/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
